//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeritriateDirector.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graphics
    {
        public int IdGraphics { get; set; }
        public string NameEvents { get; set; }
        public string PlaceEvents { get; set; }
        public System.DateTime DateEvents { get; set; }
        public System.TimeSpan TimeEvents { get; set; }
        public string TargetEvents { get; set; }
        public byte[] PhotoEvents { get; set; }
        public int IdStaff { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
