//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeritriateDirector.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Letters()
        {
            this.ResponseToTheLetters = new HashSet<ResponseToTheLetters>();
            this.WhoAnswersToWhomLetters1 = new HashSet<WhoAnswersToWhomLetters>();
        }
    
        public int IdLetters { get; set; }
        public int IdTypeLetters { get; set; }
        public string WhereLetters { get; set; }
        public int IdStaff { get; set; }
        public string SubjectLetters { get; set; }
        public System.DateTime DateReceivingOrDeparturesLetters { get; set; }
        public string TextLetters { get; set; }
        public string FromWhomLetters { get; set; }
        public string ToWhomLetters { get; set; }
        public Nullable<int> IdWhoAnswersToWhomLetters { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual TypeLetters TypeLetters { get; set; }
        public virtual WhoAnswersToWhomLetters WhoAnswersToWhomLetters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseToTheLetters> ResponseToTheLetters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WhoAnswersToWhomLetters> WhoAnswersToWhomLetters1 { get; set; }
    }
}
