//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeritriateDirector.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int IdTest { get; set; }
        public int IdStaff { get; set; }
        public int IdTestTwo { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual TestTwo TestTwo { get; set; }
    }
}
