//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeritriateDirector.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhoAnswersToWhomLetters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WhoAnswersToWhomLetters()
        {
            this.Letters = new HashSet<Letters>();
        }
    
        public int IdWhoAnswersToWhomLetters { get; set; }
        public int IdLetters { get; set; }
        public int IdResponseToTheLetters { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Letters> Letters { get; set; }
        public virtual Letters Letters1 { get; set; }
        public virtual ResponseToTheLetters ResponseToTheLetters { get; set; }
    }
}
